apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: celery-worker
  labels:
    deployment: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: wooyoung85/celery_app
          command: ['celery', '-A', 'django_app', 'worker', '-l', 'info']
          env:
            - name: REDIS_HOST
              value: redis-service
