apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - image: wooyoung85/react_app
          imagePullPolicy: Always
          name: react-app
          ports:
            - containerPort: 80